# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(1, 1), (0, 0)])),
            ],
        ),
    ]
